name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libx11-dev libgtk-3-dev

      - name: Install dlib and face_recognition
        run: |
          # Check if the custom dlib wheel exists
          if [ -f "modules/dlib-19.24.99-cp312-cp312-win_amd64.whl" ]; then
            echo "Installing from custom wheel..."
            pip install modules/dlib-19.24.99-cp312-cp312-win_amd64.whl
          else
            echo "Custom wheel not found, installing dlib from source..."
            pip install dlib==19.24.0
          fi
          # Install face_recognition_models
          pip install git+https://github.com/ageitgey/face_recognition_models
          # Install face_recognition
          pip install face-recognition

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "venv/*"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reksti-face-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}