# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Build and deploy Python app to Azure - reksti-face-api
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/reksti-face-api:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/reksti-face-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          inlineScript: |
            # Login using managed identity
            az login --identity
            
            # Make sure we're using the right subscription
            az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2000813D965B455EB723BBC624550BFB }}
            
            # Configure the web app to use the container image
            az webapp config container set \
              --name reksti-face-api \
              --resource-group DefaultResourceGroup-EUS \
              --docker-custom-image-name ghcr.io/${{ github.repository_owner }}/reksti-face-api:latest \
              --docker-registry-server-url https://ghcr.io \
              --docker-registry-server-user ${{ github.actor }} \
              --docker-registry-server-password ${{ secrets.GITHUB_TOKEN }}